# -*- coding: utf-8 -*-
"""04_LogisticRegression_SaratKumarKaniti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kUosnCB0sJ1O1DCBEDD-IcmooXunIOJ

## Logistic Regression
"""

from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
predictions = logmodel.predict(x_test)

metrics.accuracy_score(y_test,predictions)

print(classification_report(y_test, predictions))